import { CheckCircleIcon } from '@heroicons/react/20/solid'

export function Content() {
  return (
      <div className="bg-white px-6 py-32 lg:px-8">
        <div className="mx-auto max-w-3xl text-base leading-7 text-gray-700">
          <p className="text-base font-semibold leading-7 text-green-400">Introducing</p>
          <h1 className="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Personal Carbon Footprint</h1>
          <p className="mt-6 text-xl leading-8">
            Understanding your personal carbon footprint is crucial in todays world. A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions. By reducing our carbon footprint, we can help combat climate change and protect our planet.
          </p>
          <div className="mt-10 max-w-2xl">
            <p>
              There are various ways to reduce your carbon footprint, from altering your diet to reducing your energy consumption. Simple steps like using public transportation, eating less meat, and reducing, reusing, and recycling can make a significant impact.
            </p>
            <ul role="list" className="mt-8 max-w-xl space-y-8 text-gray-600">
              <li className="flex gap-x-3">
                <CheckCircleIcon aria-hidden="true" className="mt-1 h-5 w-5 flex-none text-green-400" />
                <span>
                <strong className="font-semibold text-gray-900">Transportation.</strong> Opting for carpooling, public transit, biking, or walking can substantially reduce your carbon emissions compared to driving alone.
              </span>
              </li>
              <li className="flex gap-x-3">
                <CheckCircleIcon aria-hidden="true" className="mt-1 h-5 w-5 flex-none text-green-400" />
                <span>
                <strong className="font-semibold text-gray-900">Diet.</strong> Reducing meat consumption, especially beef, and opting for more plant-based meals can lower your carbon footprint significantly.
              </span>
              </li>
              <li className="flex gap-x-3">
                <CheckCircleIcon aria-hidden="true" className="mt-1 h-5 w-5 flex-none text-green-400" />
                <span>
                <strong className="font-semibold text-gray-900">Energy Usage.</strong> Utilizing energy-efficient appliances, reducing unnecessary electricity use, and considering renewable energy sources can help reduce your carbon emissions.
              </span>
              </li>
            </ul>
            <p className="mt-8">
              Every small action counts. Simple changes in our daily routines can aggregate to significant benefits for the environment. Its all about making conscious choices and encouraging others to do the same.
            </p>
            <h2 className="mt-16 text-2xl font-bold tracking-tight text-gray-900">Steps Towards a Greener Future</h2>
            <p className="mt-6">
              Education and awareness are key. Understanding the impact of our actions on the environment and taking steps to reduce our carbon footprint can help pave the way to a sustainable future. Start small, stay committed, and together we can make a big difference.
            </p>
            <figure className="mt-10 border-l border-green-400 pl-9">
              <blockquote className="font-semibold text-gray-900">
                <p>
                  “Sustainable practices are not just beneficial for the environment; they also foster a healthier lifestyle and community. By making greener choices, we contribute to a better world for ourselves and future generations.”
                </p>
              </blockquote>
            </figure>
          </div>
        </div>
      </div>
  )
}